# https://embarkstudios.github.io/cargo-deny

targets = []
all-features = true
no-default-features = false
feature-depth = 1

[advisories]
db-path = ".cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"

[licenses]
confidence-threshold = 0.95
allow = ["MIT", "Apache-2.0"]
exceptions = [
    { allow = ["BSD-3-Clause"], crate = "encoding_rs" },
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
]
